In [1]:
import numpy as np
import scipy
import pandas
import matplotlib.pyplot as plt
import sklearn    
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
# confusion matrix in sklearn
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [3]:
data1 = pandas.read_csv("./Letters.csv")

In [4]:
data1.head(4)

,Letter,Xbox,Ybox,Width,Height,Onpix,Xbar,Ybar,X2bar,Y2bar,XYbar,X2Ybar,XY2bar,Xedge,XedgeYcor,Yedge,YedgeXcor
0,B,4,2,5,4,4,8,7,6,6,7,6,6,2,8,7,10
1,A,1,1,3,2,1,8,2,2,2,8,2,8,1,6,2,7
2,R,5,9,5,7,6,6,11,7,3,7,3,9,2,7,5,11
3,B,5,9,7,7,10,9,8,4,4,6,8,6,6,11,8,7